### ISSUE TITLE
Question about installation

### ISSUE THREAD

**Issue by FrederikPetri** [freddijkstra/XsensDOTserver#1]
Hi Fred,

I have been looking for this kind of server since i bought Xsens DOT. However, I am a little bit in doubt of how to install it correctly. I tried to follow your steps, but I am not sure it is meant for Windows?

I did setup Noble and installed Node.js, but when I try to "npm install" in XsensDOTserver folder I receive the following message:

```
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/Timeular/noble-mac.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

Can you help me?

**Comment by freddijkstra** [comment]
Hi Frederik,
I don't think that is a specific problem with this respository. When you Google some of your error messages I see several solutions that include:
- removing the node_modules directory.
- reinstalling node and npm.
- npm cache clean
(https://github.com/mapbox/node-sqlite3/issues/900)

Maybe you could try that?
Let me know how you proceeed.
Fred.

**Comment by FrederikPetri** [comment]
Hi Fred,
I will look into the solutions you provided and return with a response. 

Thanks,

**Comment by FrederikPetri** [comment]
Hi Fred,

I found a solution to the problems above. Now it seems that I cannot get node-bluetooth-hci-socket to work due to "[Issues with with bluetooth adapter 4.2](https://github.com/noble/node-bluetooth-hci-socket/issues/126)". I will try to find a solution, or wait for Xsens to make an example that require less PC skills :)
